{{- if .Values.recommender.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.recommender.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.recommender.replicas }}
  {{- with .Values.recommender.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.recommender.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vertical-pod-autoscaler.recommender.selectorLabels" . | nindent 8 }}
      {{- with .Values.recommender.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recommender.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: recommender
        image: {{ include "vertical-pod-autoscaler.recommender.image" . }}
        imagePullPolicy: {{ .Values.recommender.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.recommender.extraEnv }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        - --v=4
        - --stderrthreshold=info
        {{- with .Values.recommender.extraArgs }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: prometheus
          containerPort: 8942
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health-check
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health-check
            port: prometheus
            scheme: HTTP
          periodSeconds: 10
          failureThreshold: 3
        {{- with .Values.recommender.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.recommender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recommender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.recommender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}

