{{- if and (.Values.recommender.enabled) .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}-leader-locking
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.recommender.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - "coordination.k8s.io"
  resourceNames:
  - vpa-recommender
  - vpa-recommender-lease
  resources:
  - leases
  verbs:
  - get
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}-leader-locking
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.recommender.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}-leader-locking
subjects:
- kind: ServiceAccount
  name: {{ include "vertical-pod-autoscaler.recommender.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}

